export enum GAME_STATUS_ENUM {
  INIT,
  RUNNING,
  CLEAR,
  LOSED,
  COMPLETE,
}

export enum GAME_BOARD_ENUM {
  LEVEL,
  LEVEL_EXTEND,
  RANDOM_LEFT,
  RANDOM_RIGHT,
  SLOT,
  HIDE,
}

export enum GAME_EVENT_ENUM {
  CHECK_CLEAR = "CHECK_CLEAR",
  CHECK_LOSED = "CHECK_LOSED",
  CHECK_COMPLETE = "CHECK_COMPLETE",
  CHANGE_BOARD = "CHANGE_BOARD",
  PLAY_AUDIO = "PLAY_AUDIO",
  PLAY_BOOM = "PLAY_BOOM",
}

export enum AUDIO_EFFECT_ENUM {
  CLICKBUTTON,
  CLEAR,
  CLICKBLOCK,
  LOSE,
  WIN,
}

export enum GAME_SCENE_ENUM {
  MENU = "Menu",
  GAME = "Game",
}
